server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?servierTimezone=UTC
      username: root
      password: haoqi

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      #修改数据库自增策略
      id-type: auto
  #调处mybatisplus日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


