server:
  port: 8081
#  servlet:
#    context-path: /haoqi #http://localhost:8081/haoqi/ymlEntity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?servierTimezone=UTC
    username: root
    password: haoqi
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

  thymeleaf:
    prefix: classpath:/templates/ #\u6307\u5B9A\u6A21\u677F\u6240\u5728\u76EE\u5F55
    check-template-location: true # \u68C0\u67E5\u6A21\u677F\u8DEF\u5F84\u662F\u5426\u5B58\u5728
    cache: false #\u662F\u5426\u7F13\u5B58\uFF0Cdev\u6A21\u5F0F\u4E3Afalse\uFF0C\u907F\u514D\u8C03\u8BD5\u95EE\u9898\uFF0C\u4E0A\u7EBF\u8BBE\u4E3Atrue\u63D0\u9AD8\u6027\u80FD
    suffix: .html
    encoding: utf-8
    mode: HTML5

# debtools
test:
  name: haoqi
  age: ${random.int}